kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: ticketmanagement
  namespace: FR_CPO
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./ticketmanagement-spec.json
  policy-sequence:
    - $ref: FR_CPO:ticketmanagment_policies:1.0
